service:
  name: nest-serverless-lambda-demo

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment: # Service wide environment variables
    NODE_ENV: production
    STAGE: ${self:provider.stage}

package:
  exclude:
    - node_modules/typescript/**
    - node_modules/@types/**

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
